
export const POST_SIGNUP_REQUEST="POST_SIGNUP_REQUEST";
export const POST_SIGNUP_SUCCESS="POST_SIGNUP_SUCCESS";
export const POST_SIGNUP_FAILED="POST_SIGNUP_FAILED";

export const POST_LOGIN_REQUEST="POST_LOGIN_REQUEST";
export const POST_LOGIN_SUCCESS="POST_LOGIN_SUCCESS";
export const POST_LOGIN_FAILED="POST_LOGIN_FAILED";

